/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum T_Status implements org.apache.thrift.TEnum {
  PENDING(0),
  COMMIT(1),
  ABORT(2);

  private final int value;

  private T_Status(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static T_Status findByValue(int value) { 
    switch (value) {
      case 0:
        return PENDING;
      case 1:
        return COMMIT;
      case 2:
        return ABORT;
      default:
        return null;
    }
  }
}
